apiVersion: v1
kind: Service
metadata:
  name: myworkflow
  namespace: default
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: myworkflow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000